const assert=require('node:assert/strict');
require('../league-season.js');
const S=globalThis.SnyderLeagueSeason;
assert.equal(S.eligible('2026-09-16'),true);
for(const date of ['2026-09-17','2026-09-19','2026-09-26','2027-04-01','invalid',null])assert.equal(S.eligible(date),false);
assert.equal(S.eligible(new Date('2026-09-16T22:59:59Z')),true);
assert.equal(S.eligible(new Date('2026-09-16T23:00:00Z')),false);
const players=Array.from({length:11},(_,i)=>({id:String(i+1),name:'Player '+(i+1)}));
let state={...S.empty(),seeds:players.map(p=>p.id)};
assert.deepEqual(S.bracket(state,players).semi1.map(p=>p.id),['1','4']);
assert.deepEqual(S.bracket(state,players).semi2.map(p=>p.id),['2','3']);
assert.deepEqual(S.bracket(state,players).bottom.map(p=>p.id),['10','11']);
state=S.change(state,'sf1','4');state=S.change(state,'sf2','3');state=S.change(state,'champion','3');state=S.change(state,'spoon','11');
assert.equal(S.validate(state,players),'');
assert.equal(S.bracket(state,players).champion.name,'Player 3');
assert.equal(S.bracket(state,players).runnerUp.name,'Player 4');
assert.equal(S.bracket(state,[...players].reverse()).champion.name,'Player 3');
assert.equal(S.bracket(state,players).spoon.name,'Player 11');
assert.equal(S.change(state,'sf1','1').champion,'');
assert.equal(S.change(state,'sf1','4').champion,'3');
assert.notEqual(S.validate({...state,champion:'2'},players),'');
assert.notEqual(S.validate({...state,sf1:'2'},players),'');
assert.notEqual(S.validate({...state,spoon:'1'},players),'');
assert.notEqual(S.validate({...state,seeds:['1','1','2','3']},players),'');
assert.deepEqual(S.finalPrizes(344),{winner:240.8,runnerUp:103.2});
assert.equal(S.finalPrizes(344.01).winner+S.finalPrizes(344.01).runnerUp,344.01);
console.log('PASS: cutoff including UK midnight, seeding, saved results, corrections, invalid selections and 70/30 payouts.');
